# Generated by Django 5.2.6 on 2025-11-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meep_images/'),
        ),
    ]
