# Generated by Django 5.2.7 on 2025-12-02 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0008_comment'),
        ('musker', '0008_hashtag_meephashtag'),
    ]

    operations = [
    ]
