# Generated by Django 5.2.6 on 2025-11-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0009_comment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meep',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meep_images/'),
        ),
    ]
