# Generated by Django 5.2.7 on 2025-12-02 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0009_message_conversation'),
        ('musker', '0010_meep_image'),
    ]

    operations = [
    ]
