# Generated by Django 5.2.7 on 2025-12-05 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0009_merge_0008_comment_0008_hashtag_meephashtag'),
        ('musker', '0010_meep_image'),
    ]

    operations = [
    ]
