# Generated by Django 5.2.7 on 2025-12-06 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0011_merge_0009_message_conversation_0010_meep_image'),
        ('musker', '0013_share'),
    ]

    operations = [
    ]
