# Generated by Django 5.2.7 on 2025-12-06 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0014_merge_20251206_2123'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meep',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='meephashtag',
            name='musker_meep_created_5880a8_idx',
        ),
        migrations.RemoveField(
            model_name='meep',
            name='image',
        ),
        migrations.AddField(
            model_name='meep',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='meeps', to='musker.hashtag'),
        ),
        migrations.AddField(
            model_name='meep',
            name='is_borderline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meep',
            name='is_toxic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meep',
            name='toxicity_label',
            field=models.CharField(choices=[('safe', 'Safe'), ('borderline', 'Borderline'), ('toxic', 'Toxic')], default='safe', max_length=20),
        ),
        migrations.AddField(
            model_name='meep',
            name='toxicity_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='meep',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeps', to=settings.AUTH_USER_MODEL),
        ),
    ]
