# Generated by Django 5.2.6 on 2025-12-07 18:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0014_merge_20251206_2123'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='meephashtag',
            name='musker_meep_created_5880a8_idx',
        ),
        migrations.AlterField(
            model_name='meep',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='meep_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
