# Generated by Django 5.2.7 on 2025-12-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0015_alter_meep_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meep',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meep_images/'),
        ),
    ]
