# Generated by Django 5.2.7 on 2025-12-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0016_meep_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meep',
            name='toxicity_label',
            field=models.CharField(default='safe', max_length=20),
        ),
    ]
