# Generated by Django 5.2.7 on 2025-12-09 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0015_remove_meephashtag_musker_meep_created_5880a8_idx_and_more'),
        ('musker', '0017_alter_meep_toxicity_label'),
    ]

    operations = [
    ]
