# Generated by Django 5.2.6 on 2025-12-15 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0019_remove_meep_hashtags_alter_meep_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('TRUE', 'Accurate'), ('FALSE', 'Misleading'), ('UNVERIFIABLE', 'Needs Context'), ('OPINION', 'Opinion')], max_length=20)),
                ('confidence', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('explanation', models.TextField()),
                ('reasoning', models.TextField(blank=True)),
                ('is_ai_generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('meep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_notes', to='musker.meep')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
